image: debian/stable
packages:
  - curl
  - sbcl
sources:
  - https://github.com/communal-software/trivial-watch
tasks:
  - quicklisp: |
      curl -fsSL --retry 5 -o quicklisp.lisp https://beta.quicklisp.org/quicklisp.lisp
      sbcl --non-interactive --load quicklisp.lisp \
           --eval '(quicklisp-quickstart:install)'
      ln -s "$HOME/trivial-watch" "$HOME/quicklisp/local-projects/trivial-watch"
  - test: |
      cd trivial-watch
      WATCH_EXPECT_BACKEND=inotify tests/test.sh sbcl
