(handler-case (require :asdf)
  (error ()
    (load (or #+clisp (ext:getenv "QUICKLISP_SETUP")
              (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))))
(unless (find-package :ql)
  (load (or (uiop:getenv "QUICKLISP_SETUP")
            (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname)))))
(pushnew (truename (merge-pathnames "../" (uiop:pathname-directory-pathname *load-truename*)))
         asdf:*central-registry* :test #'equal)
(ql:quickload "trivial-watch/core" :silent t)
(assert (not (find-package :cffi)))
(assert (eq :scan (trivial-watch:backend)))
(assert (not (trivial-watch:native-p)))
(load (merge-pathnames "../examples/custom-backend.lisp" *load-truename*))
(format t "~&CFFI-free core and custom backend example loaded.~%")
(uiop:quit 0)
