(handler-case (require :asdf)
  (error ()
    (load (or #+clisp (ext:getenv "QUICKLISP_SETUP")
              (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))))

(handler-case
    (progn
      (unless (find-package :ql)
        (load (or (uiop:getenv "QUICKLISP_SETUP")
                  (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname)))))
      (pushnew (truename (merge-pathnames "../" (uiop:pathname-directory-pathname *load-truename*)))
               asdf:*central-registry* :test #'equal)
      (format t "~&Implementation: ~a ~a~%OS: ~a ~a~%Architecture: ~a~%"
              (lisp-implementation-type) (lisp-implementation-version)
              (software-type) (software-version) (machine-type))
      (funcall (read-from-string "ql:quickload") :trivial-watch/tests :silent t)
      (dolist (name '("asdf" "cffi" "bordeaux-threads" "uiop" "fiveam"))
        (let ((system (asdf:find-system name nil)))
          (when (and system (or (not (string= name "cffi")) (find-package :cffi)))
            (format t "~a: ~a~%" name (or (asdf:component-version system)
                                         (namestring (asdf:system-source-directory system)))))))
      (let* ((backend (uiop:symbol-call :trivial-watch :backend))
             (expected (uiop:getenv "WATCH_EXPECT_BACKEND")))
        (format t "Backend: ~s~%" backend)
        (when (and expected (not (string-equal expected (symbol-name backend))))
          (error "Expected backend ~a, got ~s" expected backend)))
      (when (uiop:getenv "KQUEUE_ABI_FILE")
        (unless (uiop:symbol-call :fiveam :run!
                                 (find-symbol "KQUEUE-BINDINGS-MATCH-SYSTEM-HEADERS" :trivial-watch/tests))
          (error "kqueue ABI verification failed")))
      (asdf:test-system :trivial-watch)
      (uiop:quit 0))
  (error (condition)
    (format *error-output* "~&~a~%" condition)
    (uiop:quit 1)))
