(in-package #:trivial-watch)

#+(or windows win32 mswindows)
(progn
  (cffi:define-foreign-library kernel32 (:windows "kernel32.dll") (t "kernel32.dll"))
  (cffi:use-foreign-library kernel32)
  (cffi:defcfun ("CreateFileW" %create-file :library kernel32 :convention :stdcall) :pointer
    (path :pointer) (access :uint32) (share :uint32) (security :pointer)
    (creation :uint32) (flags :uint32) (template :pointer))
  (cffi:defcfun ("CloseHandle" %close-handle :library kernel32 :convention :stdcall) :int
    (handle :pointer))
  (cffi:defcfun ("GetLastError" %last-error :library kernel32 :convention :stdcall) :uint32)
  (cffi:defcfun ("CreateIoCompletionPort" %completion-port :library kernel32 :convention :stdcall)
      :pointer (file :pointer) (port :pointer) (key :uintptr) (threads :uint32))
  (cffi:defcfun ("GetQueuedCompletionStatus" %completion :library kernel32 :convention :stdcall)
      :int (port :pointer) (bytes :pointer) (key :pointer) (overlapped :pointer) (timeout :uint32))
  (cffi:defcfun ("PostQueuedCompletionStatus" %post-completion :library kernel32 :convention :stdcall)
      :int (port :pointer) (bytes :uint32) (key :uintptr) (overlapped :pointer))
  (cffi:defcfun ("CancelIoEx" %cancel-io :library kernel32 :convention :stdcall) :int
    (handle :pointer) (overlapped :pointer))
  (cffi:defcfun ("ReadDirectoryChangesW" %directory-changes
                                   :library kernel32 :convention :stdcall) :int
    (handle :pointer) (buffer :pointer) (size :uint32) (subtree :int)
    (filter :uint32) (bytes :pointer) (overlapped :pointer) (completion :pointer))
  (cffi:defcstruct overlapped
    (internal :uintptr) (internal-high :uintptr) (offset :uint64) (event :pointer))
  (defstruct win-request path handle buffer overlapped retired)

  (defun invalid-handle ()
    (cffi:make-pointer (1- (ash 1 (* 8 (cffi:foreign-type-size :pointer))))))

  (defun open-windows-source (paths state)
    (let ((port (%completion-port (invalid-handle) (cffi:null-pointer) 0 1))
          (requests (make-path-table))
          (pending (make-hash-table)))
      (when (cffi:null-pointer-p port) (return-from open-windows-source nil))
      (labels ((free-request (request)
                 (%close-handle (win-request-handle request))
                 (cffi:foreign-free (win-request-buffer request))
                 (cffi:foreign-free (win-request-overlapped request)))
               (arm (request)
                 (when (zerop (%directory-changes
                               (win-request-handle request) (win-request-buffer request)
                               65536 0 #x1f (cffi:null-pointer)
                               (win-request-overlapped request) (cffi:null-pointer)))
                   (error "Cannot read Windows directory ~a (error ~d)"
                          (win-request-path request) (%last-error)))
                 (setf (gethash (cffi:pointer-address (win-request-overlapped request)) pending)
                       request))
               (add (path)
                 (cffi:with-foreign-string (wide path :encoding :utf-16le)
                   (let ((handle (%create-file wide 1 7 (cffi:null-pointer) 3
                                               #x42000000 (cffi:null-pointer)))
                         (request nil)
                         (registered nil))
                     (when (cffi:pointer-eq handle (invalid-handle))
                       (if (existing-path path)
                           (error "Cannot open Windows directory ~a (error ~d)" path (%last-error))
                           (return-from add nil)))
                     (unwind-protect
                          (progn
                            (setf request (make-win-request :path path :handle handle))
                            (setf (win-request-buffer request) (cffi:foreign-alloc :uint8 :count 65536)
                                  (win-request-overlapped request)
                                  (cffi:foreign-alloc :uint8 :count (cffi:foreign-type-size '(:struct overlapped))
                                                      :initial-element 0))
                            (when (cffi:null-pointer-p (%completion-port handle port 1 0))
                              (error "Cannot associate Windows directory ~a" path))
                            (arm request)
                            (setf (gethash path requests) request registered t))
                       (unless registered
                         (%close-handle handle)
                         (when (and request (win-request-buffer request))
                           (cffi:foreign-free (win-request-buffer request)))
                         (when (and request (win-request-overlapped request))
                           (cffi:foreign-free (win-request-overlapped request))))))))
               (retire (request)
                 (setf (win-request-retired request) t)
                 (%cancel-io (win-request-handle request) (win-request-overlapped request))
                 (remhash (win-request-path request) requests))
               (refresh (state)
                 (let* ((wanted (registration-paths paths state t))
                        (wanted-set (path-set wanted)))
                   (dolist (path (loop for path being the hash-keys of requests collect path))
                     (unless (gethash path wanted-set)
                       (retire (gethash path requests))))
                   (dolist (path wanted)
                     (unless (gethash path requests) (add path)))))
               (receive (closing)
                 (cffi:with-foreign-objects ((bytes :uint32) (key :uintptr) (pointer :pointer))
                   (setf (cffi:mem-ref pointer :pointer) (cffi:null-pointer))
                   (let* ((success (%completion port bytes key pointer #xffffffff))
                          (code (if (zerop success) (%last-error) 0))
                          (overlapped (cffi:mem-ref pointer :pointer)))
                     (when (cffi:null-pointer-p overlapped)
                       (unless (zerop code) (error "Windows completion wait failed: ~d" code))
                       (return-from receive nil))
                     (let* ((address (cffi:pointer-address overlapped))
                            (request (gethash address pending)))
                       (unless request (error "Unknown Windows completion"))
                       (remhash address pending)
                       (cond
                         ((or closing (win-request-retired request))
                          (free-request request) nil)
                         ((member code '(0 1022))
                          ;; Snapshot reconciliation also recovers a zero-byte overflow.
                          (handler-case (arm request)
                            (error (condition)
                              (remhash (win-request-path request) requests)
                              (free-request request)
                              (error condition)))
                          t)
                         ((member code '(5 6 995))
                          (remhash (win-request-path request) requests)
                          (free-request request) t)
                         (t (free-request request)
                            (remhash (win-request-path request) requests)
                            (error "Windows directory read failed: ~d" code)))))))
               (cleanup ()
                 (maphash (lambda (address request)
                            (declare (ignore address))
                            (%cancel-io (win-request-handle request)
                                        (win-request-overlapped request)))
                          pending)
                 (loop while (plusp (hash-table-count pending)) do (receive t))
                 (%close-handle port)))
        (handler-case
            (progn
              (refresh state)
              (make-source :wait (lambda () (receive nil)) :refresh #'refresh
                           :wake (lambda () (%post-completion port 0 0 (cffi:null-pointer)))
                           :close #'cleanup))
          (error (condition) (cleanup) (error condition))))))

  (defun %windows-watch (paths callback &key recursive events)
    (start-watch paths callback recursive events #'open-windows-source)))
