(in-package #:trivial-watch)

(defstruct source wait refresh wake close)

(defun start-watch (paths callback recursive events opener)
  (let ((source nil)
        (thread nil)
        (lock (bt2:make-lock :name "trivial-watch lifecycle"))
        (finished (bt2:make-condition-variable))
        (running t)
        (closed nil)
        (failure nil))
    (labels ((active-p () (bt2:with-lock-held (lock) running))
             (close-source ()
               (bt2:with-lock-held (lock)
                 (unless closed
                   (handler-case
                       (when source (funcall (source-close source)))
                     (error (condition) (setf failure condition)))
                   (setf running nil closed t)
                   (bt2:condition-broadcast finished))))
             (settle (paths recursive)
               ;; TODO: O(total covered bytes) per wake; narrow native reads using event hints (https://github.com/communal-software/trivial-watch/issues/1).
               (loop for before = (snapshot paths recursive)
                     for after = (progn (funcall (source-refresh source) before)
                                        (snapshot paths recursive))
                     when (or (not (active-p))
                              (equal (mapcar #'car before) (mapcar #'car after)))
                       do (funcall (source-refresh source) after)
                       and return after))
             (run (paths state)
               (unwind-protect
                    (handler-case
                        (loop while (active-p)
                              when (funcall (source-wait source))
                                do (when (active-p)
                                     (let* ((new (settle paths recursive))
                                            (batch (snapshot-events state new)))
                                       (setf state new)
                                       (when (and batch (active-p))
                                         (if events
                                             (funcall callback batch)
                                             (funcall callback))))))
                      (error (condition)
                        (bt2:with-lock-held (lock) (setf failure condition))
                        (warn "Watch stopped: ~a" condition)))
                 (close-source))))
      (handler-case
          (let* ((paths (normalize-paths paths))
                 (initial (snapshot paths recursive)))
            (unless paths (return-from start-watch nil))
            (setf source (funcall opener paths initial))
            (unless source (return-from start-watch nil))
            (let ((state (settle paths recursive)))
              (setf thread (bt2:make-thread (lambda () (run paths state))
                                           :name "trivial-watch")))
            (lambda ()
              (bt2:with-lock-held (lock)
                (when running
                  (setf running nil)
                  (unless closed (funcall (source-wake source))))
                (unless (eq thread (bt2:current-thread))
                  (loop until closed do (bt2:condition-wait finished lock))
                  (when failure (error failure))))
              nil))
        (error () (close-source) nil)))))
